name: "Install and build"

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - name: Set up node.
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x
      - name: Install and build.
        run: |
          npm ci
          npm run build
          npm run export
        env:
          CI: true
      - name: Deploy!
        uses: demurgos/ga-deploy-git@v1
        if: ${{ github.event_name == 'push' }}
        with:
          accessToken: ${{ secrets.PUSH_TOKEN }}
          commitEmail: "fredrik.forsmo+frozzbot@gmail.com"
          commitUser: "Frozzbot"
          destBranch: "master"
          srcDir: "out"
